routes/web.php
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', function () {
    return redirect()->route('login');
})->name('/');




// Guest Users
Route::middleware(['guest', 'PreventBackHistory'])->group(function () {
    Route::get('login', [App\Http\Controllers\Admin\AuthController::class, 'showLogin'])->name('login');
    Route::post('login', [App\Http\Controllers\Admin\AuthController::class, 'login'])->name('signin');
    Route::get('register', [App\Http\Controllers\Admin\AuthController::class, 'showRegister'])->name('register');
    Route::post('register', [App\Http\Controllers\Admin\AuthController::class, 'register'])->name('signup');
});




// Authenticated users
Route::middleware(['auth', 'PreventBackHistory'])->group(function () {

    // Auth Routes
    Route::get('home', fn () => redirect()->route('dashboard'))->name('home');
    Route::get('dashboard', [App\Http\Controllers\Admin\DashboardController::class, 'index'])->name('dashboard');
    Route::post('logout', [App\Http\Controllers\Admin\AuthController::class, 'Logout'])->name('logout');
    Route::get('change-theme-mode', [App\Http\Controllers\Admin\DashboardController::class, 'changeThemeMode'])->name('change-theme-mode');
    Route::get('show-change-password', [App\Http\Controllers\Admin\AuthController::class, 'showChangePassword'])->name('show-change-password');
    Route::post('change-password', [App\Http\Controllers\Admin\AuthController::class, 'changePassword'])->name('change-password');



    // Masters
    Route::resource('wards', App\Http\Controllers\Admin\Masters\WardController::class);
    Route::resource('department', App\Http\Controllers\Admin\Masters\DepartmentController::class);
    Route::resource('class', App\Http\Controllers\Admin\Masters\ClassController::class);
    Route::resource('bank', App\Http\Controllers\Admin\Masters\BankController::class);
    Route::resource('financial_year', App\Http\Controllers\Admin\Masters\FinancialYearController::class);
    Route::resource('allowance', App\Http\Controllers\Admin\Masters\AllowanceController::class);
    Route::resource('deduction', App\Http\Controllers\Admin\Masters\DeductionController::class);
    Route::resource('loan', App\Http\Controllers\Admin\Masters\LoanController::class);
    // To Change Activity Status of Loan
    Route::post('loan-activity-status/{model_id}/{btn_status}', [App\Http\Controllers\Admin\Masters\LoanController::class, 'changeStatus'])->name('loan-activity-status');

    Route::resource('designation', App\Http\Controllers\Admin\Masters\DesignationController::class);
    // Fetch departments on ward
    Route::get('fetch-departments/{ward_id}', [App\Http\Controllers\Admin\Masters\DesignationController::class, 'fetchDepartment'])->name('fetch-departments');

    Route::resource('leave-type', App\Http\Controllers\Admin\Masters\LeaveTypeController::class);
    Route::resource('pay-scale', App\Http\Controllers\Admin\Masters\PayScaleController::class);
    Route::resource('status', App\Http\Controllers\Admin\Masters\StatusController::class);



    //Employee List
    Route::resource('employee', App\Http\Controllers\Admin\Employee\EmployeeController::class);
    // Fetch designation on ward/class/department
    Route::get('fetch-designations/{ward_id}/{department_id}/{class_id}', [App\Http\Controllers\Admin\Employee\EmployeeController::class, 'fetchDesignation'])->name('fetch-designations');
    Route::get('fetch-working-years/{class_id}/{dob}', [App\Http\Controllers\Admin\Employee\EmployeeController::class, 'fetchWorkingYear'])->name('fetch-working-years');

    Route::resource('employee-status', App\Http\Controllers\Admin\Employee\EmployeeStatusController::class);
    Route::get('fetch-employee-details/{Emp_Code}', [App\Http\Controllers\Admin\Employee\EmployeeStatusController::class, 'fetchEmployeeDetails'])
        ->name('fetch-employee-details');


    // Salary Structure
    Route::resource('employee-salary', App\Http\Controllers\Admin\Employee\EmployeeSalaryController::class);
    Route::get('fetch-payscale-details/{pay_scale_id}', [App\Http\Controllers\Admin\Employee\EmployeeSalaryController::class, 'fetchpayScaleDetails'])
        ->name('fetch-payscale-details');

    Route::resource('basic-salary-increment', App\Http\Controllers\Admin\Employee\BasicSalaryIncrementController::class);
    Route::get('get-incremented-salary', [App\Http\Controllers\Admin\Employee\BasicSalaryIncrementController::class, 'getIncrementedBasicSalary'])
        ->name('get-incremented-salary');

    Route::resource('allowance-increment', App\Http\Controllers\Admin\Employee\AllowanceIncrementController::class);
    Route::get('fetch-allowance-details/{allowance_id}', [App\Http\Controllers\Admin\Employee\AllowanceIncrementController::class, 'fetchAllowanceDetails'])
        ->name('fetch-allowance-details');
    Route::get('get-incremented-allowance', [App\Http\Controllers\Admin\Employee\AllowanceIncrementController::class, 'getIncrementedAllowance'])
        ->name('get-incremented-allowance');

    Route::resource('deduction-increment', App\Http\Controllers\Admin\Employee\DeductionIncrementController::class);
    Route::get('fetch-deduction-details/{deduction_id}', [App\Http\Controllers\Admin\Employee\DeductionIncrementController::class, 'fetchDeductionDetails'])
        ->name('fetch-deduction-details');
    Route::get('get-incremented-deduction', [App\Http\Controllers\Admin\Employee\DeductionIncrementController::class, 'getIncrementedDeduction'])
        ->name('get-incremented-deduction');
    // End Salary Structure

    // Employee Loans Start
    Route::resource('employee-loans', App\Http\Controllers\Admin\Employee\EmployeeLoanController::class);
    Route::post('employee-loan-status/{model_id}/{btn_status}', [App\Http\Controllers\Admin\Employee\EmployeeLoanController::class, 'employeeLoanStatus'])->name('employee-loan-status');

    Route::resource('employee-monthly-loans', App\Http\Controllers\Admin\Employee\EmployeeMonthlyLoanController::class);
    Route::get('employee-monthly-loans/{from_date}/{to_date}', [App\Http\Controllers\Admin\Employee\EmployeeMonthlyLoanController::class, 'showEmployeeLoans'])->name('employee-monthly-loans.showEmployeeLoans');
    Route::post('employee-monthly-loan-status/{model_id}', [App\Http\Controllers\Admin\Employee\EmployeeMonthlyLoanController::class, 'employeeMonthlyLoanStatus'])->name('employee-monthly-loan-status');

    // Employee Loans End

    // Freeze Attendance
    Route::resource('freeze-attendance', App\Http\Controllers\Admin\Employee\Freeze\FreezeController::class);
    Route::get('employee-monthly-salary/{from_date}/{to_date}', [App\Http\Controllers\Admin\Employee\Freeze\FreezeController::class, 'showEmployeeSalary'])->name('employee-monthly-salary.showEmployeeSalary');
    Route::get('unfreeze-employee', [App\Http\Controllers\Admin\Employee\Freeze\FreezeController::class, 'unfreezeEmployee'])->name('unfreeze-employee');
    Route::get('freeze-employee', [App\Http\Controllers\Admin\Employee\Freeze\FreezeController::class, 'freezeEmployee'])->name('freeze-employee');

    Route::get('fetch-date-range/{month}', [App\Http\Controllers\Admin\Employee\Freeze\FreezeController::class, 'fetchDateRange'])
        ->name('fetch-date-range');
    // Freeze Attendance End


    // Reports Start
    Route::resource('salary-slips', App\Http\Controllers\Admin\Report\SalarySlipController::class);
    Route::resource('bank-statement', App\Http\Controllers\Admin\Report\BankStatementController::class);
    Route::resource('pay-sheet', App\Http\Controllers\Admin\Report\PaySheetController::class);
    Route::get('pay-sheet-pdf', [App\Http\Controllers\Admin\Report\PaySheetController::class, 'showPaySheetPDF'])->name('pay-sheet-pdf');

    Route::resource('bank-deduction-employee-report', App\Http\Controllers\Admin\Report\BankDeductionEmployeeController::class);
    Route::resource('bank-deduction-report', App\Http\Controllers\Admin\Report\BankDeductionController::class);
    Route::resource('summary-department-report', App\Http\Controllers\Admin\Report\GrandSummaryDepartmentController::class);
    Route::get('grand-summary-department-pdf', [App\Http\Controllers\Admin\Report\GrandSummaryDepartmentController::class, 'showGrandSummaryDepartmentPDF'])->name('grand-summary-department-pdf');
    Route::resource('summary-ward-report', App\Http\Controllers\Admin\Report\GrandSummaryWardController::class);
    Route::get('grand-summary-ward-pdf', [App\Http\Controllers\Admin\Report\GrandSummaryWardController::class, 'showGrandSummaryWardPDF'])->name('grand-summary-ward-pdf');
    Route::resource('summary-report', App\Http\Controllers\Admin\Report\GrandSummaryController::class);
    Route::get('grand-summary-pdf', [App\Http\Controllers\Admin\Report\GrandSummaryController::class, 'showGrandSummaryPDF'])->name('grand-summary-pdf');
    Route::resource('pay-sheet-excel', App\Http\Controllers\Admin\Report\PaySheetExcelController::class);

    Route::resource('allowance-report', App\Http\Controllers\Admin\Report\AllowanceReportController::class);
    Route::resource('deduction-report', App\Http\Controllers\Admin\Report\DeductionReportController::class);


    // Reports End

    // Users Roles n Permissions
    Route::resource('users', App\Http\Controllers\Admin\UserController::class);
    Route::get('users/{user}/toggle', [App\Http\Controllers\Admin\UserController::class, 'toggle'])->name('users.toggle');
    Route::get('users/{user}/retire', [App\Http\Controllers\Admin\UserController::class, 'retire'])->name('users.retire');

app/Http/Controllers/Admin/Employee/AllowanceIncrementController.php
<?php

namespace App\Http\Controllers\Admin\Employee;

use App\Http\Controllers\Admin\Controller;
use App\Http\Requests\Admin\Employee\StoreIncrementAllowanceRequest;
use App\Models\Allowance;
use App\Models\Department;
use Illuminate\Http\Request;
use App\Models\Clas;
use App\Models\Employee;
use App\Models\EmployeeAllowance;
use App\Models\IncrementAllowanceSalary;
use App\Models\OldEmployeeAllowance;
use Illuminate\Support\Arr;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;

class AllowanceIncrementController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        $departments = Department::latest()->get();;
        $allowances = Allowance::latest()->get();;
        $classes = Clas::latest()->get();

        return view('admin.employee.allowance-increment')->with(['departments' => $departments, 'allowances' => $allowances, 'classes' => $classes]);
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(StoreIncrementAllowanceRequest $request)
    {
        $authUser = Auth::user();

        try {
            DB::beginTransaction();
            $input = $request->validated();

            if ($input['department_id'] == 'all') {
                $input['department_id'] = 0;
            } else {
                $input['department_id'] = $input['department_id'];
            }

            if ($input['clas_id'] == 'all') {
                $input['clas_id'] = 0;
            } else {
                $input['clas_id'] = $input['clas_id'];
            }

            IncrementAllowanceSalary::create(Arr::only($input, IncrementAllowanceSalary::getFillables()));
            $emp_ids = $input['emp_id'];
            $allowance = $input['allowance_id'];

            $allowance_unique_id = $input['allowance_unique_id'];
            foreach ($emp_ids as $key => $emp_id) {

                $employee_allowance = EmployeeAllowance::where('employee_id', $emp_id)->where('id', $allowance_unique_id[$key]);

                $old_employee_allowance = OldEmployeeAllowance::where('employee_id', $emp_id)->where('allowance_id', $allowance)->latest()->first();

                $employee_allowance->update([
                    'allowance_amt' => $input['new_amount'],
                    'updated_by' => $authUser->id,
                    'updated_at' => now(),
                ]);

                $old_employee_allowance->update([
                    'end_date' => date('Y-m-d'),
                    'updated_by' => $authUser->id,
                    'updated_at' => now(),
                    'is_active' => 0,
                ]);

                $old_employee_salary_create = [
                    'employee_id' => $emp_id,
                    'Emp_Code' => $old_employee_allowance->Emp_Code,
                    'old_employee_salary_id' => $old_employee_allowance->old_employee_salary_id,
                    'allowance_id' => $allowance,
                    'allowance_amt' => $input['new_amount'],
                    'allowance_type' => $old_employee_allowance->allowance_type,
                    'is_active' => 1,
                    'applicable_date' => date('Y-m-d')
                ];

                OldEmployeeAllowance::create($old_employee_salary_create);
            }

            DB::commit();

            return response()->json(['success' => 'Basic Salary Increment successfully!']);
        } catch (\Exception $e) {
            return $this->respondWithAjax($e, 'creating', 'Basic Salary');
        }
    }

    /**
     * Display the specified resource.
     */
    public function show(string $id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(string $id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(Request $request, string $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(string $id)
    {
        //
    }

    public function fetchAllowanceDetails($allowance_id)
    {
        $allowanceDetails = Allowance::where('id', $allowance_id)->get()->first();

        if ($allowanceDetails) {
            $response = [
                'result' => 1,
                'allowanceDetails' => $allowanceDetails,
            ];
        } else {
            $response = ['result' => 0];
        }
        return $response;
    }

    public function getIncrementedAllowance(Request $request)
    {
        try {
            $departmentId = $request->input('department_id');
            $clas_id = $request->input('clas_id');
            $allowance_id = $request->input('allowance_id');
            $new_amount = $request->input('new_amount');

            $get_employees = Employee::with('department')->when(
                $departmentId == 'all',
                function ($query) {
                    return $query->latest();
                },
                function ($query) use ($departmentId, $clas_id) {
                    $query->when($departmentId != 'all', function ($subquery) use ($departmentId) {
                        $subquery->where('department_id', $departmentId);
                    })->when($clas_id != 'all', function ($subquery) use ($clas_id) {
                        $subquery->where('clas_id', $clas_id);
                    });

                    return $query->latest();
                }
            )->get();

            $incrementArr = [];

            foreach ($get_employees as $key => $employee) {

                $employeeSalary = EmployeeAllowance::with('allowance')->where('employee_id', $employee->id)
                    ->where('allowance_id', $allowance_id)->first();

                if ($employeeSalary) {
                    $incrementArr[] = [
                        'sr_no'                 =>  $key + 1,
                        'employee_uniques_id'   =>  $employee->id,
                        'allowance_unique_id'   =>  $employeeSalary->id,
                        'emp_id'                =>  $employee->employee_id,
                        'emp_name'              =>  $employee->fname . " " . $employee->mname . " " . $employee->lname,
                        'department'            =>  $employee->department->name,
                        'allowance'             =>  $employeeSalary->allowance->allowance,
                        'current_allowances'    =>  $employeeSalary->allowance_amt,
                        'increment_allowances'  =>  $new_amount,
                    ];
                }
            }

            $response = [
                'result' => 1,
                'incrementArr' => $incrementArr,
            ];

            return response()->json($response);
        } catch (\Exception $e) {
            return response()->json(['result' => 0, 'error' => $e->getMessage()]);
        }
    }
}

resources/views/admin/employee/basic-salary-increment.blade.php
<x-admin.layout>
    <x-slot name="title">Basic Salary Increment</x-slot>
    <x-slot name="heading">Basic Salary Increment</x-slot>
    {{-- <x-slot name="subheading">Test</x-slot> --}}


    <!-- Add Form -->
    <div class="row" id="addContainer">
        <div class="col-sm-12">
            <div class="card">
                <header class="card-header">
                    <h4 class="card-title">Basic Salary Increment</h4>
                </header>
                <form class="theme-form" name="addForm" id="addForm" enctype="multipart/form-data">
                    @csrf

                    <div class="card-body">
                        <div class="mb-3 row">

                            <div class="col-md-3">
                                <label class="col-form-label" for="increment_type">Select Increment Type <span class="text-danger">*</span></label>
                                <select class="form-control js-example-basic-single" name="increment_type" id="increment_type">
                                    <option value="">Select Increment Type</option>
                                    <option value="1">Regular (Next Basic slab of 7th pay chart)</option>
                                </select>
                                <span class="text-danger invalid increment_type_err"></span>
                            </div>

                            <div class="col-md-3">
                                <label class="col-form-label" for="department_id">Select Department <span class="text-danger">*</span></label>
                                <select class="form-control js-example-basic-single" name="department_id" id="department_id">
                                    <option value="">Select Department</option>
                                    <option value="all">All</option>
                                    @foreach ($departments as $department)
                                        <option value="{{ $department->id }}">{{ $department->name }}</option>
                                    @endforeach
                                </select>
                                <span class="text-danger invalid department_id_err"></span>
                            </div>

                            <div class="col-md-3">
                                <label class="col-form-label" for="applicable_date">Applicable Date <span class="text-danger">*</span></label>
                                <input type="date" name="applicable_date" id="applicable_date" class="form-control">
                                <span class="text-danger invalid applicable_date_err"></span>
                            </div>

                            <div class="col-md-3">
                                <button id="showBasicSalary" class="btn btn-primary mt-4">Show</button>
                                {{-- <button class="btn btn-warning mt-4">Cancel</button> --}}
                            </div>

                        </div>
                        @can('basic-salary-increment.create')
                        <div class="card-footer">
                            <button type="submit" class="btn btn-primary" id="addSubmit">Submit</button>
                            <button type="reset" class="btn btn-warning">Reset</button>
                        </div>
                        @endcan
                        <div class="row">
                            <div class="col-lg-12">
                                <div class="card">
                                    <div class="card-body">
                                        <div class="table-responsive">
                                            <table id="buttons-datatables" class="table table-bordered nowrap align-middle" style="width:100%">
                                                <thead>
                                                    <tr>
                                                        <th>Sr No.</th>
                                                        <th>Employee Id</th>
                                                        <th>Employee Name</th>
                                                        <th>Department</th>
                                                        <th>Current Basic Salary</th>
                                                        <th>Incremented Basic Salary</th>
                                                    </tr>
                                                </thead>
                                                <tbody>

                                                </tbody>
                                            </table>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

                </form>
            </div>
        </div>
    </div>
</x-admin.layout>


{{-- Add --}}
<script>
    $("#showBasicSalary").on("click", function(e) {
        e.preventDefault();

        var incrementType = $('#increment_type').val();
        var department_id = $('#department_id').val();
        var applicable_date = $('#applicable_date').val();

        if(incrementType != '' && department_id != '' && applicable_date != '')
        {
            var url = "{{ route('get-incremented-salary') }}";
            url += '?' + $.param({
                '_token': "{{ csrf_token() }}",
                department_id: department_id
            });

            $.ajax({
                url: url,
                type: 'GET',
                success: function(data, textStatus, jqXHR) {
                    if (!data.error) {
                        updateTable(data.incrementArr);
                    } else {
                        alert(data.error);
                    }
                },
                error: function(error, jqXHR, textStatus, errorThrown) {
                    alert("Some thing went wrong");
                },
            });

        }else{
            alert('Please select all feilds');
        }

    });

    function updateTable(data) {
        var tableBody = $('#buttons-datatables tbody');
        tableBody.empty(); // Clear existing data

        if (data.length > 0) {
            $.each(data, function(index, row) {
                var newRow = '<tr>' +
                    '<td><input type="hidden" name="salary_unique_id[]" value="'+ row.salary_unique_id +'">' + row.sr_no + '</td>' +
                    '<td><input type="hidden" name="emp_id[]" value="'+ row.employee_uniques_id +'">' + row.emp_id + '</td>' +
                    '<td>' + row.emp_name + '</td>' +
                    '<td>' + row.department + '</td>' +
                    '<td>' + row.current_basic_salary + '</td>' +
                    '<td><input type="hidden" name="incrementted_basic[]" value="'+ row.increment_basic_salary +'">' + row.increment_basic_salary + '</td>' +
                    '</tr>';
                tableBody.append(newRow);
            });
        } else {
            // Handle case where no data is returned
            var noDataRow = '<tr><td colspan="6">No data available</td></tr>';
            tableBody.append(noDataRow);
        }
    }

    $("#addForm").submit(function(e) {
        e.preventDefault();
        $("#addSubmit").prop('disabled', true);

        var formdata = new FormData(this);
        $.ajax({
            url: '{{ route('basic-salary-increment.store') }}',
            type: 'POST',
            data: formdata,
            contentType: false,
            processData: false,
            success: function(data) {
                $("#addSubmit").prop('disabled', false);
                if (!data.error2)
                    swal("Successful!", data.success, "success")
                    .then((action) => {
                        window.location.href = '{{ route('basic-salary-increment.index') }}';
                    });
                else
                    swal("Error!", data.error2, "error");
            },
            statusCode: {
                422: function(responseObject, textStatus, jqXHR) {
                    $("#addSubmit").prop('disabled', false);
                    resetErrors();
                    printErrMsg(responseObject.responseJSON.errors);
                },
                500: function(responseObject, textStatus, errorThrown) {
                    $("#addSubmit").prop('disabled', false);
                    swal("Error occured!", "Something went wrong please try again", "error");
                }
            }
        });

    });
</script>

resources/views/admin/employee/employee-status.blade.php
<x-admin.layout>
    <x-slot name="title">Employee Status</x-slot>
    <x-slot name="heading">Employee Status</x-slot>

    <div class="row">
        <div class="col-lg-12">
            <div class="card">
                @can('employee_status.create')
                    <div class="card-header">
                        <div class="row">
                            <div class="col-sm-6">
                                <div class="">
                                    <a href="{{ route('employee-status.create') }}"><button class="btn btn-primary">Add <i class="fa fa-plus"></i></button></a>
                                </div>
                            </div>
                        </div>
                    </div>
                @endcan
                <div class="card-body">
                    <div class="table-responsive">
                        <table id="buttons-datatables" class="table table-bordered nowrap align-middle" style="width:100%">
                            <thead>
                                <tr>
                                    <th>Sr No.</th>
                                    <th>Employee Id</th>
                                    <th>Status</th>
                                    <th>Remark</th>
                                    <th>Applicable Date</th>
                                    <th>Is Salary Applicable</th>
                                    <th>Salary Percent</th>
                                    <th>Action</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach ($emp_statuses as $emp_status)
                                    <tr>
                                        <td>{{ $loop->iteration }}</td>
                                        <td>{{ $emp_status->Emp_Code }}</td>
                                        <td>{{ $emp_status?->status?->name }}</td>
                                        <td>{{ $emp_status->remark }}</td>
                                        <td>{{ $emp_status->applicable_date }}</td>
                                        <td>{{ ($emp_status->is_salary_applicable == 1)?'Yes':'No' }}</td>
                                        <td>  @switch($emp_status->salary_percent)
                                                @case(1) 25% @break
                                                @case(2) 50% @break
                                                @case(3) 75% @break
                                                @case(4) 100%@break
                                                @default 0%
                                                @endswitch
                                        </td>
                                        <td>
                                            @can('employee_status.edit')
                                            <a href="{{ route('employee-status.edit',$emp_status->id) }}"><button class="edit-element btn btn-secondary px-2 py-1" title="Edit Employee Status" data-id="{{ $emp_status->id }}"><i data-feather="edit"></i></button></a>
                                            @endcan
                                            @can('employee_status.delete')
                                                <button class="btn btn-danger rem-element px-2 py-1" title="Delete Employee Status" data-id="{{ $emp_status->id }}"><i data-feather="trash-2"></i> </button>
                                            @endcan
                                        </td>
                                    </tr>
                                @endforeach
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>




</x-admin.layout>

<!-- Delete -->
<script>
    $("#buttons-datatables").on("click", ".rem-element", function(e) {
        e.preventDefault();
        swal({
                title: "Are you sure to delete this Employee status?",
                // text: "Make sure if you have filled Vendor details before proceeding further",
                icon: "info",
                buttons: ["Cancel", "Confirm"]
            })
            .then((justTransfer) => {
                if (justTransfer) {
                    var model_id = $(this).attr("data-id");
                    var url = "{{ route('employee-status.destroy', ':model_id') }}";

                    $.ajax({
                        url: url.replace(':model_id', model_id),
                        type: 'POST',
                        data: {
                            '_method': "DELETE",
                            '_token': "{{ csrf_token() }}"
                        },
                        success: function(data, textStatus, jqXHR) {
                            if (!data.error && !data.error2) {
                                swal("Success!", data.success, "success")
                                    .then((action) => {
                                        window.location.reload();
                                    });
                            } else {
                                if (data.error) {
                                    swal("Error!", data.error, "error");
                                } else {
                                    swal("Error!", data.error2, "error");
                                }
                            }
                        },
                        error: function(error, jqXHR, textStatus, errorThrown) {
                            swal("Error!", "Something went wrong", "error");
                        },
                    });
                }
            });
    });
</script>